2021-01-20 08:43:03,089 - F:/autotest/scripts1/utils/log.py[line:84] - DEBUG: debug
2021-01-20 08:43:03,091 - F:/autotest/scripts1/utils/log.py[line:85] - INFO: info
2021-01-20 08:43:03,091 - F:/autotest/scripts1/utils/log.py[line:86] - WARNING: 警告
2021-01-20 08:43:03,091 - F:/autotest/scripts1/utils/log.py[line:87] - ERROR: 报错
2021-01-20 08:43:03,091 - F:/autotest/scripts1/utils/log.py[line:88] - CRITICAL: 严重
2021-01-20 08:43:18,245 - F:/autotest/scripts1/utils/log.py[line:84] - DEBUG: debug
2021-01-20 08:43:18,245 - F:/autotest/scripts1/utils/log.py[line:85] - INFO: info
2021-01-20 08:43:18,245 - F:/autotest/scripts1/utils/log.py[line:86] - WARNING: 警告
2021-01-20 08:43:18,245 - F:/autotest/scripts1/utils/log.py[line:87] - ERROR: 报错
2021-01-20 08:43:18,245 - F:/autotest/scripts1/utils/log.py[line:88] - CRITICAL: 严重
2021-01-20 08:43:21,880 - F:/autotest/scripts1/utils/log.py[line:84] - DEBUG: debug
2021-01-20 08:43:21,881 - F:/autotest/scripts1/utils/log.py[line:85] - INFO: info
2021-01-20 08:43:21,881 - F:/autotest/scripts1/utils/log.py[line:86] - WARNING: 警告
2021-01-20 08:43:21,881 - F:/autotest/scripts1/utils/log.py[line:87] - ERROR: 报错
2021-01-20 08:43:21,881 - F:/autotest/scripts1/utils/log.py[line:88] - CRITICAL: 严重
2021-01-20 08:43:25,547 - F:/autotest/scripts1/utils/log.py[line:84] - DEBUG: debug
2021-01-20 08:43:25,547 - F:/autotest/scripts1/utils/log.py[line:85] - INFO: info
2021-01-20 08:43:25,548 - F:/autotest/scripts1/utils/log.py[line:86] - WARNING: 警告
2021-01-20 08:43:25,548 - F:/autotest/scripts1/utils/log.py[line:87] - ERROR: 报错
2021-01-20 08:43:25,548 - F:/autotest/scripts1/utils/log.py[line:88] - CRITICAL: 严重
2021-01-20 08:43:37,598 - F:/autotest/scripts1/utils/log.py[line:84] - DEBUG: debug
2021-01-20 08:43:37,598 - F:/autotest/scripts1/utils/log.py[line:85] - INFO: info
2021-01-20 08:43:37,598 - F:/autotest/scripts1/utils/log.py[line:86] - WARNING: 警告
2021-01-20 08:43:37,598 - F:/autotest/scripts1/utils/log.py[line:87] - ERROR: 报错
2021-01-20 08:43:37,598 - F:/autotest/scripts1/utils/log.py[line:88] - CRITICAL: 严重
2021-01-20 11:34:12,374 - F:/autotest/scripts1/utils/log.py[line:84] - DEBUG: debug
2021-01-20 11:34:12,374 - F:/autotest/scripts1/utils/log.py[line:85] - INFO: info
2021-01-20 11:34:12,374 - F:/autotest/scripts1/utils/log.py[line:86] - WARNING: 警告
2021-01-20 11:34:12,374 - F:/autotest/scripts1/utils/log.py[line:87] - ERROR: 报错
2021-01-20 11:34:12,374 - F:/autotest/scripts1/utils/log.py[line:88] - CRITICAL: 严重
2021-01-20 11:53:18,494 - F:/autotest/scripts1/utils/log.py[line:84] - DEBUG: debug
2021-01-20 11:53:18,494 - F:/autotest/scripts1/utils/log.py[line:85] - INFO: info
2021-01-20 11:53:18,494 - F:/autotest/scripts1/utils/log.py[line:86] - WARNING: 警告
2021-01-20 11:53:18,494 - F:/autotest/scripts1/utils/log.py[line:87] - ERROR: 报错
2021-01-20 11:53:18,494 - F:/autotest/scripts1/utils/log.py[line:88] - CRITICAL: 严重
